- hosts: all
  become: true

  roles:
    - role: geerlingguy.pip
      tags: install_dependencies

  tasks:
    - name: create env
      ansible.builtin.template:
        src: env.j2
        dest: .env
        mode: "644"
    - name: install redmine
      community.docker.docker_container:
        name: redmine
        image: redmine:5.1.1
        ports:
          - "{{ REDMINE_PORT }}:3000"
        env_file: .env

- hosts: webservers
  become: true

  roles:
    - role: datadog.datadog
      tags: install_dependencies